import json
from pathlib import Path

PROBLEMS_DIR = Path(__file__).resolve().parent.parent / "problems"

problems = [
    # === ARRAYS & HASHING ===
    ("contains_duplicate", "Contains Duplicate", "easy", "nums", "list[int]", "bool",
     "def contains_duplicate(nums: list[int]) -> bool:\n    pass",
     [{"input": {"nums": [1,2,3,1]}, "expected": True},
      {"input": {"nums": [1,2,3,4]}, "expected": False},
      {"input": {"nums": [1,1,1,3,3,4,3,2,4,2]}, "expected": True}]),
    ("valid_anagram", "Valid Anagram", "easy", "s,t", "str,str", "bool",
     "def is_anagram(s: str, t: str) -> bool:\n    pass",
     [{"input": {"s": "anagram", "t": "nagaram"}, "expected": True},
      {"input": {"s": "rat", "t": "car"}, "expected": False}]),
    ("two_sum", "Two Sum", "easy", "nums,target", "list[int],int", "list[int]",
     "def two_sum(nums: list[int], target: int) -> list[int]:\n    pass",
     [{"input": {"nums": [2,7,11,15], "target": 9}, "expected": [0,1]},
      {"input": {"nums": [3,2,4], "target": 6}, "expected": [1,2]},
      {"input": {"nums": [3,3], "target": 6}, "expected": [0,1]}]),
    ("group_anagrams", "Group Anagrams", "medium", "strs", "list[str]", "list[list[str]]",
     "def group_anagrams(strs: list[str]) -> list[list[str]]:\n    pass",
     [{"input": {"strs": ["eat","tea","tan","ate","nat","bat"]}, "expected": [["bat"],["nat","tan"],["ate","eat","tea"]]},
      {"input": {"strs": [""]}, "expected": [[""]]},
      {"input": {"strs": ["a"]}, "expected": [["a"]]}]),
    ("top_k_frequent_elements", "Top K Frequent Elements", "medium", "nums,k", "list[int],int", "list[int]",
     "def top_k_frequent(nums: list[int], k: int) -> list[int]:\n    pass",
     [{"input": {"nums": [1,1,1,2,2,3], "k": 2}, "expected": [1,2]},
      {"input": {"nums": [1], "k": 1}, "expected": [1]}]),
    ("product_of_array_except_self", "Product of Array Except Self", "medium", "nums", "list[int]", "list[int]",
     "def product_except_self(nums: list[int]) -> list[int]:\n    pass",
     [{"input": {"nums": [1,2,3,4]}, "expected": [24,12,8,6]},
      {"input": {"nums": [-1,1,0,-3,3]}, "expected": [0,0,9,0,0]}]),
    ("valid_sudoku", "Valid Sudoku", "medium", "board", "list[list[str]]", "bool",
     "def is_valid_sudoku(board: list[list[str]]) -> bool:\n    pass", []),
    ("encode_decode_strings", "Encode and Decode Strings", "medium", "strs", "list[str]", "str",
     "def encode(strs: list[str]) -> str:\n    pass\n\ndef decode(s: str) -> list[str]:\n    pass", []),
    ("longest_consecutive_sequence", "Longest Consecutive Sequence", "medium", "nums", "list[int]", "int",
     "def longest_consecutive(nums: list[int]) -> int:\n    pass",
     [{"input": {"nums": [100,4,200,1,3,2]}, "expected": 4},
      {"input": {"nums": [0,3,7,2,5,8,4,6,0,1]}, "expected": 9}]),
    ("contains_duplicate_ii", "Contains Duplicate II", "easy", "nums,k", "list[int],int", "bool",
     "def contains_nearby_duplicate(nums: list[int], k: int) -> bool:\n    pass", []),

    # === TWO POINTERS ===
    ("valid_palindrome", "Valid Palindrome", "easy", "s", "str", "bool",
     "def is_palindrome(s: str) -> bool:\n    pass",
     [{"input": {"s": "A man, a plan, a canal: Panama"}, "expected": True},
      {"input": {"s": "race a car"}, "expected": False},
      {"input": {"s": " "}, "expected": True}]),
    ("two_sum_ii", "Two Sum II - Input Array Is Sorted", "medium", "numbers,target", "list[int],int", "list[int]",
     "def two_sum(numbers: list[int], target: int) -> list[int]:\n    pass",
     [{"input": {"numbers": [2,7,11,15], "target": 9}, "expected": [1,2]},
      {"input": {"numbers": [2,3,4], "target": 6}, "expected": [1,3]},
      {"input": {"numbers": [-1,0], "target": -1}, "expected": [1,2]}]),
    ("three_sum", "3Sum", "medium", "nums", "list[int]", "list[list[int]]",
     "def three_sum(nums: list[int]) -> list[list[int]]:\n    pass",
     [{"input": {"nums": [-1,0,1,2,-1,-4]}, "expected": [[-1,-1,2],[-1,0,1]]},
      {"input": {"nums": [0,1,1]}, "expected": []},
      {"input": {"nums": [0,0,0]}, "expected": [[0,0,0]]}]),
    ("container_with_most_water", "Container With Most Water", "medium", "height", "list[int]", "int",
     "def max_area(height: list[int]) -> int:\n    pass",
     [{"input": {"height": [1,8,6,2,5,4,8,3,7]}, "expected": 49},
      {"input": {"height": [1,1]}, "expected": 1}]),
    ("trapping_rain_water", "Trapping Rain Water", "hard", "height", "list[int]", "int",
     "def trap(height: list[int]) -> int:\n    pass",
     [{"input": {"height": [0,1,0,2,1,0,1,3,2,1,2,1]}, "expected": 6},
      {"input": {"height": [4,2,0,3,2,5]}, "expected": 9}]),
    ("next_permutation", "Next Permutation", "medium", "nums", "list[int]", "None",
     "def next_permutation(nums: list[int]) -> None:\n    \"\"\"Modify nums in-place.\"\"\"\n    pass", []),
    ("remove_duplicates_from_sorted_array", "Remove Duplicates from Sorted Array", "easy", "nums", "list[int]", "int",
     "def remove_duplicates(nums: list[int]) -> int:\n    pass", []),
    ("verifying_alien_dictionary", "Verifying an Alien Dictionary", "easy", "words,order", "list[str],str", "bool",
     "def is_alien_sorted(words: list[str], order: str) -> bool:\n    pass", []),

    # === SLIDING WINDOW ===
    ("best_time_to_buy_and_sell_stock", "Best Time to Buy and Sell Stock", "easy", "prices", "list[int]", "int",
     "def max_profit(prices: list[int]) -> int:\n    pass",
     [{"input": {"prices": [7,1,5,3,6,4]}, "expected": 5},
      {"input": {"prices": [7,6,4,3,1]}, "expected": 0}]),
    ("longest_substring_without_repeating", "Longest Substring Without Repeating Characters", "medium", "s", "str", "int",
     "def length_of_longest_substring(s: str) -> int:\n    pass",
     [{"input": {"s": "abcabcbb"}, "expected": 3},
      {"input": {"s": "bbbbb"}, "expected": 1},
      {"input": {"s": "pwwkew"}, "expected": 3}]),
    ("longest_repeating_character_replacement", "Longest Repeating Character Replacement", "medium", "s,k", "str,int", "int",
     "def character_replacement(s: str, k: int) -> int:\n    pass",
     [{"input": {"s": "ABAB", "k": 2}, "expected": 4},
      {"input": {"s": "AABABBA", "k": 1}, "expected": 4}]),
    ("permutation_in_string", "Permutation in String", "medium", "s1,s2", "str,str", "bool",
     "def check_inclusion(s1: str, s2: str) -> bool:\n    pass",
     [{"input": {"s1": "ab", "s2": "eidbaooo"}, "expected": True},
      {"input": {"s1": "ab", "s2": "eidboaoo"}, "expected": False}]),
    ("minimum_window_substring", "Minimum Window Substring", "hard", "s,t", "str,str", "str",
     "def min_window(s: str, t: str) -> str:\n    pass",
     [{"input": {"s": "ADOBECODEBANC", "t": "ABC"}, "expected": "BANC"},
      {"input": {"s": "a", "t": "a"}, "expected": "a"},
      {"input": {"s": "a", "t": "aa"}, "expected": ""}]),
    ("sliding_window_maximum", "Sliding Window Maximum", "hard", "nums,k", "list[int],int", "list[int]",
     "def max_sliding_window(nums: list[int], k: int) -> list[int]:\n    pass",
     [{"input": {"nums": [1,3,-1,-3,5,3,6,7], "k": 3}, "expected": [3,3,5,5,6,7]},
      {"input": {"nums": [1], "k": 1}, "expected": [1]}]),

    # === STACK ===
    ("valid_parentheses", "Valid Parentheses", "easy", "s", "str", "bool",
     "def is_valid(s: str) -> bool:\n    pass",
     [{"input": {"s": "()"}, "expected": True},
      {"input": {"s": "()[]{}"}, "expected": True},
      {"input": {"s": "(]"}, "expected": False},
      {"input": {"s": "([)]"}, "expected": False},
      {"input": {"s": "{[]}"}, "expected": True}]),
    ("min_stack", "Min Stack", "medium", "", "", "None",
     "class MinStack:\n    def __init__(self):\n        pass\n    def push(self, val: int) -> None:\n        pass\n    def pop(self) -> None:\n        pass\n    def top(self) -> int:\n        pass\n    def get_min(self) -> int:\n        pass", []),
    ("evaluate_reverse_polish_notation", "Evaluate Reverse Polish Notation", "medium", "tokens", "list[str]", "int",
     "def eval_rpn(tokens: list[str]) -> int:\n    pass",
     [{"input": {"tokens": ["2","1","+","3","*"]}, "expected": 9},
      {"input": {"tokens": ["4","13","5","/","+"]}, "expected": 6},
      {"input": {"tokens": ["10","6","9","3","+","-11","*","/","*","17","+","5","+"]}, "expected": 22}]),
    ("generate_parentheses", "Generate Parentheses", "medium", "n", "int", "list[str]",
     "def generate_parenthesis(n: int) -> list[str]:\n    pass",
     [{"input": {"n": 3}, "expected": ["((()))","(()())","(())()","()(())","()()()"]},
      {"input": {"n": 1}, "expected": ["()"]}]),
    ("daily_temperatures", "Daily Temperatures", "medium", "temperatures", "list[int]", "list[int]",
     "def daily_temperatures(temperatures: list[int]) -> list[int]:\n    pass",
     [{"input": {"temperatures": [73,74,75,71,69,72,76,73]}, "expected": [1,1,4,2,1,1,0,0]},
      {"input": {"temperatures": [30,40,50,60]}, "expected": [1,1,1,0]},
      {"input": {"temperatures": [30,60,90]}, "expected": [1,1,0]}]),
    ("car_fleet", "Car Fleet", "medium", "target,position,speed", "int,list[int],list[int]", "int",
     "def car_fleet(target: int, position: list[int], speed: list[int]) -> int:\n    pass",
     [{"input": {"target": 12, "position": [10,8,0,5,3], "speed": [2,4,1,1,3]}, "expected": 3},
      {"input": {"target": 10, "position": [3], "speed": [3]}, "expected": 1}]),
    ("largest_rectangle_in_histogram", "Largest Rectangle in Histogram", "hard", "heights", "list[int]", "int",
     "def largest_rectangle_area(heights: list[int]) -> int:\n    pass",
     [{"input": {"heights": [2,1,5,6,2,3]}, "expected": 10},
      {"input": {"heights": [2,4]}, "expected": 4}]),
    ("minimum_remove_to_make_valid_parentheses", "Minimum Remove to Make Valid Parentheses", "medium", "s", "str", "str",
     "def min_remove_to_make_valid(s: str) -> str:\n    pass",
     [{"input": {"s": "lee(t(c)o)de)"}, "expected": "lee(t(c)o)de"},
      {"input": {"s": "a)b(c)d"}, "expected": "ab(c)d"},
      {"input": {"s": "))(("}, "expected": ""}]),
    ("longest_valid_parentheses", "Longest Valid Parentheses", "hard", "s", "str", "int",
     "def longest_valid_parentheses(s: str) -> int:\n    pass",
     [{"input": {"s": "(()"}, "expected": 2},
      {"input": {"s": ")()())"}, "expected": 4},
      {"input": {"s": ""}, "expected": 0}]),
    ("max_stack", "Max Stack", "hard", "", "", "None",
     "class MaxStack:\n    def __init__(self):\n        pass\n    def push(self, val: int) -> None:\n        pass\n    def pop(self) -> int:\n        pass\n    def top(self) -> int:\n        pass\n    def peek_max(self) -> int:\n        pass\n    def pop_max(self) -> int:\n        pass", []),

    # === BINARY SEARCH ===
    ("binary_search", "Binary Search", "easy", "nums,target", "list[int],int", "int",
     "def search(nums: list[int], target: int) -> int:\n    pass",
     [{"input": {"nums": [-1,0,3,5,9,12], "target": 9}, "expected": 4},
      {"input": {"nums": [-1,0,3,5,9,12], "target": 2}, "expected": -1}]),
    ("search_a_2d_matrix", "Search a 2D Matrix", "medium", "matrix,target", "list[list[int]],int", "bool",
     "def search_matrix(matrix: list[list[int]], target: int) -> bool:\n    pass",
     [{"input": {"matrix": [[1,3,5,7],[10,11,16,20],[23,30,34,60]], "target": 3}, "expected": True},
      {"input": {"matrix": [[1,3,5,7],[10,11,16,20],[23,30,34,60]], "target": 13}, "expected": False}]),
    ("koko_eating_bananas", "Koko Eating Bananas", "medium", "piles,h", "list[int],int", "int",
     "def min_eating_speed(piles: list[int], h: int) -> int:\n    pass",
     [{"input": {"piles": [3,6,7,11], "h": 8}, "expected": 4},
      {"input": {"piles": [30,11,23,4,20], "h": 5}, "expected": 30},
      {"input": {"piles": [30,11,23,4,20], "h": 6}, "expected": 23}]),
    ("find_minimum_in_rotated_sorted_array", "Find Minimum in Rotated Sorted Array", "medium", "nums", "list[int]", "int",
     "def find_min(nums: list[int]) -> int:\n    pass",
     [{"input": {"nums": [3,4,5,1,2]}, "expected": 1},
      {"input": {"nums": [4,5,6,7,0,1,2]}, "expected": 0},
      {"input": {"nums": [11,13,15,17]}, "expected": 11}]),
    ("search_in_rotated_sorted_array", "Search in Rotated Sorted Array", "medium", "nums,target", "list[int],int", "int",
     "def search(nums: list[int], target: int) -> int:\n    pass",
     [{"input": {"nums": [4,5,6,7,0,1,2], "target": 0}, "expected": 4},
      {"input": {"nums": [4,5,6,7,0,1,2], "target": 3}, "expected": -1},
      {"input": {"nums": [1], "target": 0}, "expected": -1}]),
    ("time_based_key_value_store", "Time Based Key-Value Store", "medium", "", "", "None",
     "class TimeMap:\n    def __init__(self):\n        pass\n    def set(self, key: str, value: str, timestamp: int) -> None:\n        pass\n    def get(self, key: str, timestamp: int) -> str:\n        pass", []),
    ("median_of_two_sorted_arrays", "Median of Two Sorted Arrays", "hard", "nums1,nums2", "list[int],list[int]", "float",
     "def find_median_sorted_arrays(nums1: list[int], nums2: list[int]) -> float:\n    pass",
     [{"input": {"nums1": [1,3], "nums2": [2]}, "expected": 2.0},
      {"input": {"nums1": [1,2], "nums2": [3,4]}, "expected": 2.5}])
]

# === LINKED LIST ===
linked_list_problems = [
    ("reverse_linked_list", "Reverse Linked List", "easy", "head", "list[int]", "list[int]",
     "def reverse_list(head: list[int]) -> list[int]:\n    pass",
     [{"input": {"head": [1,2,3,4,5]}, "expected": [5,4,3,2,1]},
      {"input": {"head": [1,2]}, "expected": [2,1]},
      {"input": {"head": []}, "expected": []}]),
    ("merge_two_sorted_lists", "Merge Two Sorted Lists", "easy", "list1,list2", "list[int],list[int]", "list[int]",
     "def merge_two_lists(list1: list[int], list2: list[int]) -> list[int]:\n    pass",
     [{"input": {"list1": [1,2,4], "list2": [1,3,4]}, "expected": [1,1,2,3,4,4]},
      {"input": {"list1": [], "list2": []}, "expected": []},
      {"input": {"list1": [], "list2": [0]}, "expected": [0]}]),
    ("reorder_list", "Reorder List", "medium", "head", "list[int]", "list[int]",
     "def reorder_list(head: list[int]) -> list[int]:\n    pass",
     [{"input": {"head": [1,2,3,4]}, "expected": [1,4,2,3]},
      {"input": {"head": [1,2,3,4,5]}, "expected": [1,5,2,4,3]}]),
    ("remove_nth_node_from_end", "Remove Nth Node From End of List", "medium", "head,n", "list[int],int", "list[int]",
     "def remove_nth_from_end(head: list[int], n: int) -> list[int]:\n    pass",
     [{"input": {"head": [1,2,3,4,5], "n": 2}, "expected": [1,2,3,5]},
      {"input": {"head": [1], "n": 1}, "expected": []},
      {"input": {"head": [1,2], "n": 1}, "expected": [1]}]),
    ("copy_list_with_random_pointer", "Copy List with Random Pointer", "medium", "head", "list[list[int]]", "list[list[int]]",
     "def copy_random_list(head: list[list[int]]) -> list[list[int]]:\n    \"\"\"Each node is [val, random_index] where random_index is index or None\"\"\"\n    pass", []),
    ("add_two_numbers", "Add Two Numbers", "medium", "l1,l2", "list[int],list[int]", "list[int]",
     "def add_two_numbers(l1: list[int], l2: list[int]) -> list[int]:\n    pass",
     [{"input": {"l1": [2,4,3], "l2": [5,6,4]}, "expected": [7,0,8]},
      {"input": {"l1": [0], "l2": [0]}, "expected": [0]},
      {"input": {"l1": [9,9,9,9,9,9,9], "l2": [9,9,9,9]}, "expected": [8,9,9,9,0,0,0,1]}]),
    ("linked_list_cycle", "Linked List Cycle", "easy", "head,pos", "list[int],int", "bool",
     "def has_cycle(head: list[int], pos: int) -> bool:\n    \"\"\"pos is the index where tail connects (-1 for no cycle)\"\"\"\n    pass",
     [{"input": {"head": [3,2,0,-4], "pos": 1}, "expected": True},
      {"input": {"head": [1,2], "pos": 0}, "expected": True},
      {"input": {"head": [1], "pos": -1}, "expected": False}]),
    ("find_the_duplicate_number", "Find the Duplicate Number", "medium", "nums", "list[int]", "int",
     "def find_duplicate(nums: list[int]) -> int:\n    pass",
     [{"input": {"nums": [1,3,4,2,2]}, "expected": 2},
      {"input": {"nums": [3,1,3,4,2]}, "expected": 3}]),
    ("lru_cache", "LRU Cache", "medium", "", "", "None",
     "class LRUCache:\n    def __init__(self, capacity: int):\n        pass\n    def get(self, key: int) -> int:\n        pass\n    def put(self, key: int, value: int) -> None:\n        pass", []),
    ("merge_k_sorted_lists", "Merge K Sorted Lists", "hard", "lists", "list[list[int]]", "list[int]",
     "def merge_k_lists(lists: list[list[int]]) -> list[int]:\n    pass",
     [{"input": {"lists": [[1,4,5],[1,3,4],[2,6]]}, "expected": [1,1,2,3,4,4,5,6]},
      {"input": {"lists": []}, "expected": []},
      {"input": {"lists": [[]]}, "expected": []}]),
    ("reverse_nodes_in_k_group", "Reverse Nodes in k-Group", "hard", "head,k", "list[int],int", "list[int]",
     "def reverse_k_group(head: list[int], k: int) -> list[int]:\n    pass",
     [{"input": {"head": [1,2,3,4,5], "k": 2}, "expected": [2,1,4,3,5]},
      {"input": {"head": [1,2,3,4,5], "k": 3}, "expected": [3,2,1,4,5]}]),
    ("palindrome_linked_list", "Palindrome Linked List", "easy", "head", "list[int]", "bool",
     "def is_palindrome(head: list[int]) -> bool:\n    pass",
     [{"input": {"head": [1,2,2,1]}, "expected": True},
      {"input": {"head": [1,2]}, "expected": False}]),
    ("middle_of_linked_list", "Middle of the Linked List", "easy", "head", "list[int]", "list[int]",
     "def middle_node(head: list[int]) -> list[int]:\n    pass",
     [{"input": {"head": [1,2,3,4,5]}, "expected": [3,4,5]},
      {"input": {"head": [1,2,3,4,5,6]}, "expected": [4,5,6]}]),
]

# === TREES ===
tree_problems = [
    ("invert_binary_tree", "Invert Binary Tree", "easy", "root", "list[int]", "list[int]",
     "def invert_tree(root: list[int]) -> list[int]:\n    pass",
     [{"input": {"root": [4,2,7,1,3,6,9]}, "expected": [4,7,2,9,6,3,1]},
      {"input": {"root": [2,1,3]}, "expected": [2,3,1]},
      {"input": {"root": []}, "expected": []}]),
    ("maximum_depth_of_binary_tree", "Maximum Depth of Binary Tree", "easy", "root", "list[int]", "int",
     "def max_depth(root: list[int]) -> int:\n    pass",
     [{"input": {"root": [3,9,20,None,None,15,7]}, "expected": 3},
      {"input": {"root": [1,None,2]}, "expected": 2}])
]

remaining_tree = [
    ("diameter_of_binary_tree", "Diameter of Binary Tree", "easy", "root", "list[int]", "int",
     "def diameter_of_binary_tree(root: list[int]) -> int:\n    pass", []),
    ("balanced_binary_tree", "Balanced Binary Tree", "easy", "root", "list[int]", "bool",
     "def is_balanced(root: list[int]) -> bool:\n    pass", []),
    ("same_tree", "Same Tree", "easy", "p,q", "list[int],list[int]", "bool", "def is_same_tree(p: list[int], q: list[int]) -> bool:\n    pass", []),
    ("subtree_of_another_tree", "Subtree of Another Tree", "easy", "root,sub_root", "list[int],list[int]", "bool",
     "def is_subtree(root: list[int], sub_root: list[int]) -> bool:\n    pass", []),
    ("symmetric_tree", "Symmetric Tree", "easy", "root", "list[int]", "bool",
     "def is_symmetric(root: list[int]) -> bool:\n    pass",
     [{"input": {"root": [1,2,2,3,4,4,3]}, "expected": True},
      {"input": {"root": [1,2,2,None,3,None,3]}, "expected": False}]),
    ("lowest_common_ancestor_of_bst", "Lowest Common Ancestor of a Binary Search Tree", "medium", "root,p,q", "list[int],int,int", "int",
     "def lowest_common_ancestor(root: list[int], p: int, q: int) -> int:\n    pass",
     [{"input": {"root": [6,2,8,0,4,7,9,None,None,3,5], "p": 2, "q": 8}, "expected": 6},
      {"input": {"root": [6,2,8,0,4,7,9,None,None,3,5], "p": 2, "q": 4}, "expected": 2}]),
    ("binary_tree_level_order_traversal", "Binary Tree Level Order Traversal", "medium", "root", "list[int]", "list[list[int]]",
     "def level_order(root: list[int]) -> list[list[int]]:\n    pass",
     [{"input": {"root": [3,9,20,None,None,15,7]}, "expected": [[3],[9,20],[15,7]]},
      {"input": {"root": [1]}, "expected": [[1]]},
      {"input": {"root": []}, "expected": []}]),
    ("binary_tree_right_side_view", "Binary Tree Right Side View", "medium", "root", "list[int]", "list[int]",
     "def right_side_view(root: list[int]) -> list[int]:\n    pass", []),
    ("count_good_nodes_in_binary_tree", "Count Good Nodes in Binary Tree", "medium", "root", "list[int]", "int",
     "def good_nodes(root: list[int]) -> int:\n    pass", []),
    ("validate_binary_search_tree", "Validate Binary Search Tree", "medium", "root", "list[int]", "bool",
     "def is_valid_bst(root: list[int]) -> bool:\n    pass",
     [{"input": {"root": [2,1,3]}, "expected": True},
      {"input": {"root": [5,1,4,None,None,3,6]}, "expected": False}]),
    ("kth_smallest_element_in_bst", "Kth Smallest Element in a BST", "medium", "root,k", "list[int],int", "int",
     "def kth_smallest(root: list[int], k: int) -> int:\n    pass", []),
    ("construct_binary_tree_from_preorder_inorder", "Construct Binary Tree from Preorder and Inorder Traversal", "medium", "preorder,inorder", "list[int],list[int]", "list[int]",
     "def build_tree(preorder: list[int], inorder: list[int]) -> list[int]:\n    pass", []),
    ("binary_tree_maximum_path_sum", "Binary Tree Maximum Path Sum", "hard", "root", "list[int]", "int",
     "def max_path_sum(root: list[int]) -> int:\n    pass", []),
    ("serialize_deserialize_binary_tree", "Serialize and Deserialize Binary Tree", "hard", "root", "list[int]", "str",
     "def serialize(root: list[int]) -> str:\n    pass\n\ndef deserialize(data: str) -> list[int]:\n    pass", []),
    ("flatten_binary_tree_to_linked_list", "Flatten Binary Tree to Linked List", "medium", "root", "list[int]", "list[int]",
     "def flatten(root: list[int]) -> list[int]:\n    pass", []),
    ("binary_tree_zigzag_level_order", "Binary Tree Zigzag Level Order Traversal", "medium", "root", "list[int]", "list[list[int]]",
     "def zigzag_level_order(root: list[int]) -> list[list[int]]:\n    pass", []),
    ("find_leaves_of_binary_tree", "Find Leaves of Binary Tree", "medium", "root", "list[int]", "list[list[int]]",
     "def find_leaves(root: list[int]) -> list[list[int]]:\n    pass", []),
]

# === HEAP / PRIORITY QUEUE ===
heap_problems = [
    ("kth_largest_element_in_a_stream", "Kth Largest Element in a Stream", "easy", "k,nums", "int,list[int]", "int",
     "class KthLargest:\n    def __init__(self, k: int, nums: list[int]):\n        pass\n    def add(self, val: int) -> int:\n        pass", []),
    ("last_stone_weight", "Last Stone Weight", "easy", "stones", "list[int]", "int",
     "def last_stone_weight(stones: list[int]) -> int:\n    pass",
     [{"input": {"stones": [2,7,4,1,8,1]}, "expected": 1}]),
    ("k_closest_points_to_origin", "K Closest Points to Origin", "medium", "points,k", "list[list[int]],int", "list[list[int]]",
     "def k_closest(points: list[list[int]], k: int) -> list[list[int]]:\n    pass", []),
    ("kth_largest_element_in_an_array", "Kth Largest Element in an Array", "medium", "nums,k", "list[int],int", "int",
     "def find_kth_largest(nums: list[int], k: int) -> int:\n    pass",
     [{"input": {"nums": [3,2,1,5,6,4], "k": 2}, "expected": 5},
      {"input": {"nums": [3,2,3,1,2,4,5,5,6], "k": 4}, "expected": 4}]),
    ("task_scheduler", "Task Scheduler", "medium", "tasks,n", "list[str],int", "int",
     "def least_interval(tasks: list[str], n: int) -> int:\n    pass",
     [{"input": {"tasks": ["A","A","A","B","B","B"], "n": 2}, "expected": 8},
      {"input": {"tasks": ["A","C","A","B","D","B"], "n": 1}, "expected": 6},
      {"input": {"tasks": ["A","A","A","B","B","B"], "n": 3}, "expected": 10}]),
    ("design_twitter", "Design Twitter", "medium", "", "", "None",
     "class Twitter:\n    def __init__(self):\n        pass\n    def post_tweet(self, userId: int, tweetId: int) -> None:\n        pass\n    def get_news_feed(self, userId: int) -> list[int]:\n        pass\n    def follow(self, followerId: int, followeeId: int) -> None:\n        pass\n    def unfollow(self, followerId: int, followeeId: int) -> None:\n        pass", []),
    ("find_median_from_data_stream", "Find Median from Data Stream", "hard", "", "", "None",
     "class MedianFinder:\n    def __init__(self):\n        pass\n    def add_num(self, num: int) -> None:\n        pass\n    def find_median(self) -> float:\n        pass", []),
]

# === BACKTRACKING ===
backtracking_problems = [
    ("subsets", "Subsets", "medium", "nums", "list[int]", "list[list[int]]",
     "def subsets(nums: list[int]) -> list[list[int]]:\n    pass",
     [{"input": {"nums": [1,2,3]}, "expected": [[],[1],[2],[1,2],[3],[1,3],[2,3],[1,2,3]]},
      {"input": {"nums": [0]}, "expected": [[],[0]]}]),
    ("combination_sum", "Combination Sum", "medium", "candidates,target", "list[int],int", "list[list[int]]",
     "def combination_sum(candidates: list[int], target: int) -> list[list[int]]:\n    pass",
     [{"input": {"candidates": [2,3,6,7], "target": 7}, "expected": [[2,2,3],[7]]},
      {"input": {"candidates": [2,3,5], "target": 8}, "expected": [[2,2,2,2],[2,3,3],[3,5]]}]),
    ("permutations", "Permutations", "medium", "nums", "list[int]", "list[list[int]]",
     "def permute(nums: list[int]) -> list[list[int]]:\n    pass",
     [{"input": {"nums": [1,2,3]}, "expected": [[1,2,3],[1,3,2],[2,1,3],[2,3,1],[3,1,2],[3,2,1]]},
      {"input": {"nums": [0,1]}, "expected": [[0,1],[1,0]]}]),
    ("subsets_ii", "Subsets II", "medium", "nums", "list[int]", "list[list[int]]",
     "def subsets_with_dup(nums: list[int]) -> list[list[int]]:\n    pass",
     [{"input": {"nums": [1,2,2]}, "expected": [[],[1],[1,2],[1,2,2],[2],[2,2]]},
      {"input": {"nums": [0]}, "expected": [[],[0]]}]),
    ("combination_sum_ii", "Combination Sum II", "medium", "candidates,target", "list[int],int", "list[list[int]]",
     "def combination_sum2(candidates: list[int], target: int) -> list[list[int]]:\n    pass", []),
    ("word_search", "Word Search", "medium", "board,word", "list[list[str]],str", "bool",
     "def exist(board: list[list[str]], word: str) -> bool:\n    pass",
     [{"input": {"board": [["A","B","C","E"],["S","F","C","S"],["A","D","E","E"]], "word": "ABCCED"}, "expected": True},
      {"input": {"board": [["A","B","C","E"],["S","F","C","S"],["A","D","E","E"]], "word": "SEE"}, "expected": True},
      {"input": {"board": [["A","B","C","E"],["S","F","C","S"],["A","D","E","E"]], "word": "ABCB"}, "expected": False}]),
    ("palindrome_partitioning", "Palindrome Partitioning", "medium", "s", "str", "list[list[str]]",
     "def partition(s: str) -> list[list[str]]:\n    pass", []),
    ("letter_combinations_of_phone_number", "Letter Combinations of a Phone Number", "medium", "digits", "str", "list[str]",
     "def letter_combinations(digits: str) -> list[str]:\n    pass",
     [{"input": {"digits": "23"}, "expected": ["ad","ae","af","bd","be","bf","cd","ce","cf"]},
      {"input": {"digits": ""}, "expected": []},
      {"input": {"digits": "2"}, "expected": ["a","b","c"]}]),
    ("n_queens", "N-Queens", "hard", "n", "int", "list[list[str]]",
     "def solve_n_queens(n: int) -> list[list[str]]:\n    pass", []),
]

# === GRAPHS ===
graph_problems = [
    ("number_of_islands", "Number of Islands", "medium", "grid", "list[list[str]]", "int",
     "def num_islands(grid: list[list[str]]) -> int:\n    pass",
     [{"input": {"grid": [["1","1","1","1","0"],["1","1","0","1","0"],["1","1","0","0","0"],["0","0","0","0","0"]]}, "expected": 1},
      {"input": {"grid": [["1","1","0","0","0"],["1","1","0","0","0"],["0","0","1","0","0"],["0","0","0","1","1"]]}, "expected": 3}]),
    ("clone_graph", "Clone Graph", "medium", "node", "list[list[int]]", "list[list[int]]",
     "def clone_graph(node: list[list[int]]) -> list[list[int]]:\n    pass", []),
    ("max_area_of_island", "Max Area of Island", "medium", "grid", "list[list[int]]", "int",
     "def max_area_of_island(grid: list[list[int]]) -> int:\n    pass",
     [{"input": {"grid": [[0,0,1,0,0,0,0,1,0,0,0,0,0],[0,0,0,0,0,0,0,1,1,1,0,0,0],[0,1,1,0,1,0,0,0,0,0,0,0,0],[0,1,0,0,1,1,0,0,1,0,1,0,0],[0,1,0,0,1,1,0,0,1,1,1,0,0],[0,0,0,0,0,0,0,0,0,0,1,0,0],[0,0,0,0,0,0,0,1,1,1,0,0,0],[0,0,0,0,0,0,0,1,1,0,0,0,0]]}, "expected": 6}]),
    ("pacific_atlantic_water_flow", "Pacific Atlantic Water Flow", "medium", "heights", "list[list[int]]", "list[list[int]]",
     "def pacific_atlantic(heights: list[list[int]]) -> list[list[int]]:\n    pass", []),
    ("surrounded_regions", "Surrounded Regions", "medium", "board", "list[list[str]]", "None",
     "def solve(board: list[list[str]]) -> None:\n    \"\"\"Modify board in-place.\"\"\"\n    pass", []),
    ("rotting_oranges", "Rotting Oranges", "medium", "grid", "list[list[int]]", "int",
     "def oranges_rotting(grid: list[list[int]]) -> int:\n    pass",
     [{"input": {"grid": [[2,1,1],[1,1,0],[0,1,1]]}, "expected": 4},
      {"input": {"grid": [[2,1,1],[0,1,1],[1,0,1]]}, "expected": -1}]),
    ("walls_and_gates", "Walls and Gates", "medium", "rooms", "list[list[int]]", "None",
     "def walls_and_gates(rooms: list[list[int]]) -> None:\n    \"\"\"Modify rooms in-place. INF = 2147483647, GATE = 0, WALL = -1\"\"\"\n    pass", []),
    ("course_schedule", "Course Schedule", "medium", "num_courses,prerequisites", "int,list[list[int]]", "bool",
     "def can_finish(num_courses: int, prerequisites: list[list[int]]) -> bool:\n    pass",
     [{"input": {"num_courses": 2, "prerequisites": [[1,0]]}, "expected": True},
      {"input": {"num_courses": 2, "prerequisites": [[1,0],[0,1]]}, "expected": False}]),
    ("course_schedule_ii", "Course Schedule II", "medium", "num_courses,prerequisites", "int,list[list[int]]", "list[int]",
     "def find_order(num_courses: int, prerequisites: list[list[int]]) -> list[int]:\n    pass", []),
    ("redundant_connection", "Redundant Connection", "medium", "edges", "list[list[int]]", "list[int]",
     "def find_redundant_connection(edges: list[list[int]]) -> list[int]:\n    pass", []),
    ("number_of_connected_components", "Number of Connected Components in an Undirected Graph", "medium", "n,edges", "int,list[list[int]]", "int",
     "def count_components(n: int, edges: list[list[int]]) -> int:\n    pass", []),
    ("graph_valid_tree", "Graph Valid Tree", "medium", "n,edges", "int,list[list[int]]", "bool",
     "def valid_tree(n: int, edges: list[list[int]]) -> bool:\n    pass", []),
    ("word_ladder", "Word Ladder", "hard", "begin_word,end_word,word_list", "str,str,list[str]", "int",
     "def ladder_length(begin_word: str, end_word: str, word_list: list[str]) -> int:\n    pass",
     [{"input": {"begin_word": "hit", "end_word": "cog", "word_list": ["hot","dot","dog","lot","log","cog"]}, "expected": 5},
      {"input": {"begin_word": "hit", "end_word": "cog", "word_list": ["hot","dot","dog","lot","log"]}, "expected": 0}]),
    ("reconstruct_itinerary", "Reconstruct Itinerary", "hard", "tickets", "list[list[str]]", "list[str]",
     "def find_itinerary(tickets: list[list[str]]) -> list[str]:\n    pass", []),
    ("min_cost_to_connect_all_points", "Min Cost to Connect All Points", "medium", "points", "list[list[int]]", "int",
     "def min_cost_connect_points(points: list[list[int]]) -> int:\n    pass", []),
    ("network_delay_time", "Network Delay Time", "medium", "times,n,k", "list[list[int]],int,int", "int",
     "def network_delay_time(times: list[list[int]], n: int, k: int) -> int:\n    pass", []),
    ("swim_in_rising_water", "Swim in Rising Water", "hard", "grid", "list[list[int]]", "int",
     "def swim_in_water(grid: list[list[int]]) -> int:\n    pass", []),
    ("alien_dictionary", "Alien Dictionary", "hard", "words", "list[str]", "str",
     "def alien_order(words: list[str]) -> str:\n    pass", []),
    ("cheapest_flights_within_k_stops", "Cheapest Flights Within K Stops", "medium", "n,flights,src,dst,k", "int,list[list[int]],int,int,int", "int",
     "def find_cheapest_price(n: int, flights: list[list[int]], src: int, dst: int, k: int) -> int:\n    pass", []),
]

# === 1-D DYNAMIC PROGRAMMING ===
dp1_problems = [
    ("climbing_stairs", "Climbing Stairs", "easy", "n", "int", "int",
     "def climb_stairs(n: int) -> int:\n    pass",
     [{"input": {"n": 2}, "expected": 2}, {"input": {"n": 3}, "expected": 3}]),
    ("min_cost_climbing_stairs", "Min Cost Climbing Stairs", "easy", "cost", "list[int]", "int",
     "def min_cost_climbing_stairs(cost: list[int]) -> int:\n    pass",
     [{"input": {"cost": [10,15,20]}, "expected": 15},
      {"input": {"cost": [1,100,1,1,1,100,1,1,100,1]}, "expected": 6}]),
    ("house_robber", "House Robber", "medium", "nums", "list[int]", "int",
     "def rob(nums: list[int]) -> int:\n    pass",
     [{"input": {"nums": [1,2,3,1]}, "expected": 4},
      {"input": {"nums": [2,7,9,3,1]}, "expected": 12}]),
    ("house_robber_ii", "House Robber II", "medium", "nums", "list[int]", "int",
     "def rob(nums: list[int]) -> int:\n    pass",
     [{"input": {"nums": [2,3,2]}, "expected": 3},
      {"input": {"nums": [1,2,3,1]}, "expected": 4}]),
    ("longest_palindromic_substring", "Longest Palindromic Substring", "medium", "s", "str", "str",
     "def longest_palindrome(s: str) -> str:\n    pass",
     [{"input": {"s": "babad"}, "expected": "bab"},
      {"input": {"s": "cbbd"}, "expected": "bb"}]),
    ("palindromic_substrings", "Palindromic Substrings", "medium", "s", "str", "int",
     "def count_substrings(s: str) -> int:\n    pass",
     [{"input": {"s": "abc"}, "expected": 3},
      {"input": {"s": "aaa"}, "expected": 6}]),
    ("decode_ways", "Decode Ways", "medium", "s", "str", "int",
     "def num_decodings(s: str) -> int:\n    pass",
     [{"input": {"s": "12"}, "expected": 2},
      {"input": {"s": "226"}, "expected": 3},
      {"input": {"s": "06"}, "expected": 0}]),
    ("coin_change", "Coin Change", "medium", "coins,amount", "list[int],int", "int",
     "def coin_change(coins: list[int], amount: int) -> int:\n    pass",
     [{"input": {"coins": [1,2,5], "amount": 11}, "expected": 3},
      {"input": {"coins": [2], "amount": 3}, "expected": -1},
      {"input": {"coins": [1], "amount": 0}, "expected": 0}]),
    ("maximum_product_subarray", "Maximum Product Subarray", "medium", "nums", "list[int]", "int",
     "def max_product(nums: list[int]) -> int:\n    pass",
     [{"input": {"nums": [2,3,-2,4]}, "expected": 6},
      {"input": {"nums": [-2,0,-1]}, "expected": 0}]),
    ("word_break", "Word Break", "medium", "s,word_dict", "str,list[str]", "bool",
     "def word_break(s: str, word_dict: list[str]) -> bool:\n    pass",
     [{"input": {"s": "leetcode", "word_dict": ["leet","code"]}, "expected": True},
      {"input": {"s": "applepenapple", "word_dict": ["apple","pen"]}, "expected": True},
      {"input": {"s": "catsandog", "word_dict": ["cats","dog","sand","and","cat"]}, "expected": False}]),
    ("longest_increasing_subsequence", "Longest Increasing Subsequence", "medium", "nums", "list[int]", "int",
     "def length_of_lis(nums: list[int]) -> int:\n    pass",
     [{"input": {"nums": [10,9,2,5,3,7,101,18]}, "expected": 4},
      {"input": {"nums": [0,1,0,3,2,3]}, "expected": 4},
      {"input": {"nums": [7,7,7,7,7,7,7]}, "expected": 1}]),
    ("partition_equal_subset_sum", "Partition Equal Subset Sum", "medium", "nums", "list[int]", "bool",
     "def can_partition(nums: list[int]) -> bool:\n    pass",
     [{"input": {"nums": [1,5,11,5]}, "expected": True},
      {"input": {"nums": [1,2,3,5]}, "expected": False}]),
]

# === 2-D DYNAMIC PROGRAMMING ===
dp2_problems = [
    ("unique_paths", "Unique Paths", "medium", "m,n", "int,int", "int",
     "def unique_paths(m: int, n: int) -> int:\n    pass",
     [{"input": {"m": 3, "n": 7}, "expected": 28},
      {"input": {"m": 3, "n": 2}, "expected": 3}]),
    ("longest_common_subsequence", "Longest Common Subsequence", "medium", "text1,text2", "str,str", "int",
     "def longest_common_subsequence(text1: str, text2: str) -> int:\n    pass",
     [{"input": {"text1": "abcde", "text2": "ace"}, "expected": 3},
      {"input": {"text1": "abc", "text2": "abc"}, "expected": 3},
      {"input": {"text1": "abc", "text2": "def"}, "expected": 0}]),
    ("best_time_to_buy_and_sell_stock_with_cooldown", "Best Time to Buy and Sell Stock with Cooldown", "medium", "prices", "list[int]", "int",
     "def max_profit(prices: list[int]) -> int:\n    pass",
     [{"input": {"prices": [1,2,3,0,2]}, "expected": 3},
      {"input": {"prices": [1]}, "expected": 0}]),
    ("coin_change_ii", "Coin Change II", "medium", "amount,coins", "int,list[int]", "int",
     "def change(amount: int, coins: list[int]) -> int:\n    pass",
     [{"input": {"amount": 5, "coins": [1,2,5]}, "expected": 4},
      {"input": {"amount": 3, "coins": [2]}, "expected": 0},
      {"input": {"amount": 10, "coins": [10]}, "expected": 1}]),
    ("target_sum", "Target Sum", "medium", "nums,target", "list[int],int", "int",
     "def find_target_sum_ways(nums: list[int], target: int) -> int:\n    pass", []),
    ("interleaving_string", "Interleaving String", "medium", "s1,s2,s3", "str,str,str", "bool",
     "def is_interleave(s1: str, s2: str, s3: str) -> bool:\n    pass", []),
    ("longest_increasing_path_in_a_matrix", "Longest Increasing Path in a Matrix", "hard", "matrix", "list[list[int]]", "int",
     "def longest_increasing_path(matrix: list[list[int]]) -> int:\n    pass", []),
    ("distinct_subsequences", "Distinct Subsequences", "hard", "s,t", "str,str", "int",
     "def num_distinct(s: str, t: str) -> int:\n    pass", []),
    ("edit_distance", "Edit Distance", "medium", "word1,word2", "str,str", "int",
     "def min_distance(word1: str, word2: str) -> int:\n    pass",
     [{"input": {"word1": "horse", "word2": "ros"}, "expected": 3},
      {"input": {"word1": "intention", "word2": "execution"}, "expected": 5}]),
    ("burst_balloons", "Burst Balloons", "hard", "nums", "list[int]", "int",
     "def max_coins(nums: list[int]) -> int:\n    pass", []),
    ("regular_expression_matching", "Regular Expression Matching", "hard", "s,p", "str,str", "bool",
     "def is_match(s: str, p: str) -> bool:\n    pass",
     [{"input": {"s": "aa", "p": "a"}, "expected": False},
      {"input": {"s": "aa", "p": "a*"}, "expected": True},
      {"input": {"s": "ab", "p": ".*"}, "expected": True}]),
]

# === GREEDY ===
greedy_problems = [
    ("maximum_subarray", "Maximum Subarray", "medium", "nums", "list[int]", "int",
     "def max_sub_array(nums: list[int]) -> int:\n    pass",
     [{"input": {"nums": [-2,1,-3,4,-1,2,1,-5,4]}, "expected": 6},
      {"input": {"nums": [1]}, "expected": 1},
      {"input": {"nums": [5,4,-1,7,8]}, "expected": 23}]),
    ("jump_game", "Jump Game", "medium", "nums", "list[int]", "bool",
     "def can_jump(nums: list[int]) -> bool:\n    pass",
     [{"input": {"nums": [2,3,1,1,4]}, "expected": True},
      {"input": {"nums": [3,2,1,0,4]}, "expected": False}]),
    ("jump_game_ii", "Jump Game II", "medium", "nums", "list[int]", "int",
     "def jump(nums: list[int]) -> int:\n    pass",
     [{"input": {"nums": [2,3,1,1,4]}, "expected": 2}]),
    ("gas_station", "Gas Station", "medium", "gas,cost", "list[int],list[int]", "int",
     "def can_complete_circuit(gas: list[int], cost: list[int]) -> int:\n    pass",
     [{"input": {"gas": [1,2,3,4,5], "cost": [3,4,5,1,2]}, "expected": 3},
      {"input": {"gas": [2,3,4], "cost": [3,4,3]}, "expected": -1}]),
    ("hand_of_straights", "Hand of Straights", "medium", "hand,group_size", "list[int],int", "bool",
     "def is_n_straight_hand(hand: list[int], group_size: int) -> bool:\n    pass", []),
    ("merge_triplets_to_form_target", "Merge Triplets to Form Target Triplet", "medium", "triplets,target", "list[list[int]],list[int]", "bool",
     "def merge_triplets(triplets: list[list[int]], target: list[int]) -> bool:\n    pass", []),
    ("partition_labels", "Partition Labels", "medium", "s", "str", "list[int]",
     "def partition_labels(s: str) -> list[int]:\n    pass",
     [{"input": {"s": "ababcbacadefegdehijhklij"}, "expected": [9,7,8]},
      {"input": {"s": "eccbbbbdec"}, "expected": [10]}]),
    ("valid_parenthesis_string", "Valid Parenthesis String", "medium", "s", "str", "bool",
     "def check_valid_string(s: str) -> bool:\n    pass",
     [{"input": {"s": "()"}, "expected": True},
      {"input": {"s": "(*)"}, "expected": True},
      {"input": {"s": "(*))"}, "expected": True}]),
]

# === INTERVALS ===
interval_problems = [
    ("insert_interval", "Insert Interval", "medium", "intervals,new_interval", "list[list[int]],list[int]", "list[list[int]]",
     "def insert(intervals: list[list[int]], new_interval: list[int]) -> list[list[int]]:\n    pass",
     [{"input": {"intervals": [[1,3],[6,9]], "new_interval": [2,5]}, "expected": [[1,5],[6,9]]},
      {"input": {"intervals": [[1,2],[3,5],[6,7],[8,10],[12,16]], "new_interval": [4,8]}, "expected": [[1,2],[3,10],[12,16]]}]),
    ("merge_intervals", "Merge Intervals", "medium", "intervals", "list[list[int]]", "list[list[int]]",
     "def merge(intervals: list[list[int]]) -> list[list[int]]:\n    pass",
     [{"input": {"intervals": [[1,3],[2,6],[8,10],[15,18]]}, "expected": [[1,6],[8,10],[15,18]]},
      {"input": {"intervals": [[1,4],[4,5]]}, "expected": [[1,5]]}]),
    ("non_overlapping_intervals", "Non-overlapping Intervals", "medium", "intervals", "list[list[int]]", "int",
     "def erase_overlap_intervals(intervals: list[list[int]]) -> int:\n    pass",
     [{"input": {"intervals": [[1,2],[2,3],[3,4],[1,3]]}, "expected": 1},
      {"input": {"intervals": [[1,2],[1,2],[1,2]]}, "expected": 2}]),
    ("meeting_rooms", "Meeting Rooms", "easy", "intervals", "list[list[int]]", "bool",
     "def can_attend_meetings(intervals: list[list[int]]) -> bool:\n    pass", []),
    ("meeting_rooms_ii", "Meeting Rooms II", "medium", "intervals", "list[list[int]]", "int",
     "def min_meeting_rooms(intervals: list[list[int]]) -> int:\n    pass",
     [{"input": {"intervals": [[0,30],[5,10],[15,20]]}, "expected": 2},
      {"input": {"intervals": [[7,10],[2,4]]}, "expected": 1}]),
    ("minimum_interval_to_include_query", "Minimum Interval to Include Each Query", "hard", "intervals,queries", "list[list[int]],list[int]", "list[int]",
     "def min_interval(intervals: list[list[int]], queries: list[int]) -> list[int]:\n    pass", []),
    ("remove_interval", "Remove Interval", "medium", "intervals,toBeRemoved", "list[list[int]],list[int]", "list[list[int]]",
     "def remove_interval(intervals: list[list[int]], to_be_removed: list[int]) -> list[list[int]]:\n    pass", []),
]

# === MATRICES ===
matrix_problems = [
    ("rotate_image", "Rotate Image", "medium", "matrix", "list[list[int]]", "None",
     "def rotate(matrix: list[list[int]]) -> None:\n    \"\"\"Modify matrix in-place.\"\"\"\n    pass",
     []),
    ("spiral_matrix", "Spiral Matrix", "medium", "matrix", "list[list[int]]", "list[int]",
     "def spiral_order(matrix: list[list[int]]) -> list[int]:\n    pass",
     [{"input": {"matrix": [[1,2,3],[4,5,6],[7,8,9]]}, "expected": [1,2,3,6,9,8,7,4,5]},
      {"input": {"matrix": [[1,2,3,4],[5,6,7,8],[9,10,11,12]]}, "expected": [1,2,3,4,8,12,11,10,9,5,6,7]}]),
    ("set_matrix_zeroes", "Set Matrix Zeroes", "medium", "matrix", "list[list[int]]", "None",
     "def set_zeroes(matrix: list[list[int]]) -> None:\n    \"\"\"Modify matrix in-place.\"\"\"\n    pass", []),
    ("game_of_life", "Game of Life", "medium", "board", "list[list[int]]", "None",
     "def game_of_life(board: list[list[int]]) -> None:\n    \"\"\"Modify board in-place.\"\"\"\n    pass", []),
]

# === MATH & OTHER ===
misc_problems = [
    ("happy_number", "Happy Number", "easy", "n", "int", "bool",
     "def is_happy(n: int) -> bool:\n    pass",
     [{"input": {"n": 19}, "expected": True},
      {"input": {"n": 2}, "expected": False}]),
    ("plus_one", "Plus One", "easy", "digits", "list[int]", "list[int]",
     "def plus_one(digits: list[int]) -> list[int]:\n    pass",
     [{"input": {"digits": [1,2,3]}, "expected": [1,2,4]},
      {"input": {"digits": [4,3,2,1]}, "expected": [4,3,2,2]},
      {"input": {"digits": [9]}, "expected": [1,0]}]),
    ("pow_x_n", "Pow(x, n)", "medium", "x,n", "float,int", "float",
     "def my_pow(x: float, n: int) -> float:\n    pass",
     [{"input": {"x": 2.0, "n": 10}, "expected": 1024.0},
      {"input": {"x": 2.1, "n": 3}, "expected": 9.261},
      {"input": {"x": 2.0, "n": -2}, "expected": 0.25}]),
    ("multiply_strings", "Multiply Strings", "medium", "num1,num2", "str,str", "str",
     "def multiply(num1: str, num2: str) -> str:\n    pass",
     [{"input": {"num1": "2", "num2": "3"}, "expected": "6"},
      {"input": {"num1": "123", "num2": "456"}, "expected": "56088"}]),
    ("detect_squares", "Detect Squares", "medium", "", "", "None",
     "class DetectSquares:\n    def __init__(self):\n        pass\n    def add(self, point: list[int]) -> None:\n        pass\n    def count(self, point: list[int]) -> int:\n        pass", []),
    ("single_number", "Single Number", "easy", "nums", "list[int]", "int",
     "def single_number(nums: list[int]) -> int:\n    pass",
     [{"input": {"nums": [2,2,1]}, "expected": 1},
      {"input": {"nums": [4,1,2,1,2]}, "expected": 4},
      {"input": {"nums": [1]}, "expected": 1}]),
    ("number_of_1_bits", "Number of 1 Bits", "easy", "n", "int", "int",
     "def hamming_weight(n: int) -> int:\n    pass",
     [{"input": {"n": 11}, "expected": 3},
      {"input": {"n": 128}, "expected": 1},
      {"input": {"n": 4294967293}, "expected": 31}]),
    ("counting_bits", "Counting Bits", "easy", "n", "int", "list[int]",
     "def count_bits(n: int) -> list[int]:\n    pass",
     [{"input": {"n": 2}, "expected": [0,1,1]},
      {"input": {"n": 5}, "expected": [0,1,1,2,1,2]}]),
    ("reverse_bits", "Reverse Bits", "easy", "n", "int", "int",
     "def reverse_bits(n: int) -> int:\n    pass",
     [{"input": {"n": 43261596}, "expected": 964176192},
      {"input": {"n": 4294967293}, "expected": 3221225471}]),
    ("missing_number", "Missing Number", "easy", "nums", "list[int]", "int",
     "def missing_number(nums: list[int]) -> int:\n    pass",
     [{"input": {"nums": [3,0,1]}, "expected": 2},
      {"input": {"nums": [0,1]}, "expected": 2},
      {"input": {"nums": [9,6,4,2,3,5,7,0,1]}, "expected": 8}]),
    ("sum_of_two_integers", "Sum of Two Integers", "medium", "a,b", "int,int", "int",
     "def get_sum(a: int, b: int) -> int:\n    pass",
     [{"input": {"a": 1, "b": 2}, "expected": 3},
      {"input": {"a": 2, "b": 3}, "expected": 5}]),
    ("reverse_integer", "Reverse Integer", "medium", "x", "int", "int",
     "def reverse(x: int) -> int:\n    pass",
     [{"input": {"x": 123}, "expected": 321},
      {"input": {"x": -123}, "expected": -321},
      {"input": {"x": 120}, "expected": 21}]),
    ("roman_to_integer", "Roman to Integer", "easy", "s", "str", "int",
     "def roman_to_int(s: str) -> int:\n    pass",
     [{"input": {"s": "III"}, "expected": 3},
      {"input": {"s": "LVIII"}, "expected": 58},
      {"input": {"s": "MCMXCIV"}, "expected": 1994}]),
    ("pascals_triangle", "Pascal's Triangle", "easy", "num_rows", "int", "list[list[int]]",
     "def generate(num_rows: int) -> list[list[int]]:\n    pass",
     [{"input": {"num_rows": 5}, "expected": [[1],[1,1],[1,2,1],[1,3,3,1],[1,4,6,4,1]]},
      {"input": {"num_rows": 1}, "expected": [[1]]}]),
    ("fizz_buzz", "Fizz Buzz", "easy", "n", "int", "list[str]",
     "def fizz_buzz(n: int) -> list[str]:\n    pass",
     [{"input": {"n": 3}, "expected": ["1","2","Fizz"]},
      {"input": {"n": 5}, "expected": ["1","2","Fizz","4","Buzz"]},
      {"input": {"n": 15}, "expected": ["1","2","Fizz","4","Buzz","Fizz","7","8","Fizz","Buzz","11","Fizz","13","14","FizzBuzz"]}]),
    ("longest_common_prefix", "Longest Common Prefix", "easy", "strs", "list[str]", "str",
     "def longest_common_prefix(strs: list[str]) -> str:\n    pass",
     [{"input": {"strs": ["flower","flow","flight"]}, "expected": "fl"},
      {"input": {"strs": ["dog","racecar","car"]}, "expected": ""}]),
    ("majority_element", "Majority Element", "easy", "nums", "list[int]", "int",
     "def majority_element(nums: list[int]) -> int:\n    pass",
     [{"input": {"nums": [3,2,3]}, "expected": 3},
      {"input": {"nums": [2,2,1,1,1,2,2]}, "expected": 2}]),
    ("merge_sorted_array", "Merge Sorted Array", "easy", "nums1,m,nums2,n", "list[int],int,list[int],int", "None",
     "def merge(nums1: list[int], m: int, nums2: list[int], n: int) -> None:\n    \"\"\"Modify nums1 in-place.\"\"\"\n    pass", []),
    ("largest_number", "Largest Number", "medium", "nums", "list[int]", "str",
     "def largest_number(nums: list[int]) -> str:\n    pass", []),
    ("sort_list", "Sort List", "medium", "head", "list[int]", "list[int]",
     "def sort_list(head: list[int]) -> list[int]:\n    pass", []),
    ("sort_colors", "Sort Colors", "medium", "nums", "list[int]", "None",
     "def sort_colors(nums: list[int]) -> None:\n    \"\"\"Modify nums in-place.\"\"\"\n    pass",
     [{"input": {"nums": [2,0,2,1,1,0]}, "expected": [0,0,1,1,2,2]},
      {"input": {"nums": [2,0,1]}, "expected": [0,1,2]}]),
    ("text_justification", "Text Justification", "hard", "words,max_width", "list[str],int", "list[str]",
     "def full_justify(words: list[str], max_width: int) -> list[str]:\n    pass", []),
    ("first_missing_positive", "First Missing Positive", "hard", "nums", "list[int]", "int",
     "def first_missing_positive(nums: list[int]) -> int:\n    pass",
     [{"input": {"nums": [1,2,0]}, "expected": 3},
      {"input": {"nums": [3,4,-1,1]}, "expected": 2},
      {"input": {"nums": [7,8,9,11,12]}, "expected": 1}]),
    ("find_first_and_last_position", "Find First and Last Position of Element in Sorted Array", "medium", "nums,target", "list[int],int", "list[int]",
     "def search_range(nums: list[int], target: int) -> list[int]:\n    pass",
     [{"input": {"nums": [5,7,7,8,8,10], "target": 8}, "expected": [3,4]},
      {"input": {"nums": [5,7,7,8,8,10], "target": 6}, "expected": [-1,-1]},
      {"input": {"nums": [], "target": 0}, "expected": [-1,-1]}]),
    ("race_car", "Race Car", "hard", "target", "int", "int",
     "def racecar(target: int) -> int:\n    pass", []),
    ("number_of_provinces", "Number of Provinces", "medium", "is_connected", "list[list[int]]", "int",
     "def find_circle_num(is_connected: list[list[int]]) -> int:\n    pass", []),
    ("find_the_celebrity", "Find the Celebrity", "medium", "n", "int", "int",
     "def find_celebrity(n: int) -> int:\n    \"\"\"You have access to knows(a, b) function.\"\"\"\n    pass", []),
    ("insert_delete_getrandom", "Insert Delete GetRandom O(1)", "medium", "", "", "None",
     "class RandomizedSet:\n    def __init__(self):\n        pass\n    def insert(self, val: int) -> bool:\n        pass\n    def remove(self, val: int) -> bool:\n        pass\n    def get_random(self) -> int:\n        pass", []),
    ("logger_rate_limiter", "Logger Rate Limiter", "easy", "", "", "None",
     "class Logger:\n    def __init__(self):\n        pass\n    def should_print_message(self, timestamp: int, message: str) -> bool:\n        pass", []),
    ("design_tic_tac_toe", "Design Tic-Tac-Toe", "medium", "", "", "None",
     "class TicTacToe:\n    def __init__(self, n: int):\n        pass\n    def move(self, row: int, col: int, player: int) -> int:\n        pass", []),
    ("moving_average_from_data_stream", "Moving Average from Data Stream", "easy", "", "", "None",
     "class MovingAverage:\n    def __init__(self, size: int):\n        pass\n    def next(self, val: int) -> float:\n        pass", []),
    ("high_five", "High Five", "easy", "items", "list[list[int]]", "list[list[int]]",
     "def high_five(items: list[list[int]]) -> list[list[int]]:\n    \"\"\"Each item is [student_id, score]\"\"\"\n    pass", []),
    ("employee_free_time", "Employee Free Time", "hard", "schedule", "list[list[list[int]]]", "list[list[int]]",
     "def employee_free_time(schedule: list[list[list[int]]]) -> list[list[int]]:\n    pass", []),
    ("implement_trie", "Implement Trie (Prefix Tree)", "medium", "", "", "None",
     "class Trie:\n    def __init__(self):\n        pass\n    def insert(self, word: str) -> None:\n        pass\n    def search(self, word: str) -> bool:\n        pass\n    def starts_with(self, prefix: str) -> bool:\n        pass", []),
    ("add_and_search_word", "Add and Search Word", "medium", "", "", "None",
     "class WordDictionary:\n    def __init__(self):\n        pass\n    def add_word(self, word: str) -> None:\n        pass\n    def search(self, word: str) -> bool:\n        pass", []),
    ("word_search_ii", "Word Search II", "hard", "board,words", "list[list[str]],list[str]", "list[str]",
     "def find_words(board: list[list[str]], words: list[str]) -> list[str]:\n    pass", []),
]

def slugify(title):
    return title.lower().replace("'", "").replace("(", "").replace(")", "").replace(" - ", "_").replace(" ", "_").replace(",", "").replace("-", "_")

def write_problem(pid, title, difficulty, params, ptypes, rtype, starter, test_cases):
    param_list = []
    if params:
        names = params.split(",")
        types = ptypes.split(",")
        for n, t in zip(names, types):
            param_list.append({"name": n.strip(), "type": t.strip()})

    data = {
        "id": pid,
        "title": title,
        "difficulty": difficulty,
        "description": f"Solve the **{title}** problem on LeetCode.\n\nFunction signature: `{starter.split(chr(10))[0]}`",
        "function_name": starter.split("(")[0].split()[-1] if "def " in starter else starter.split("class ")[1].split(":")[0],
        "params": param_list,
        "return_type": rtype,
        "starter_code": starter,
        "test_cases": test_cases
    }
    if "class " in starter and "def " not in starter:
        data["function_name"] = starter.split("class ")[1].split(":")[0]
        data["problem_type"] = "class"

    filepath = PROBLEMS_DIR / f"{pid}.json"
    with open(filepath, "w") as f:
        json.dump(data, f, indent=2)
    print(f"  Created {pid}.json")

# Remove old problem files first
for f in PROBLEMS_DIR.glob("*.json"):
    f.unlink()

all_problems = (
    problems + linked_list_problems + tree_problems + remaining_tree +
    heap_problems + backtracking_problems + graph_problems +
    dp1_problems + dp2_problems + greedy_problems +
    interval_problems + matrix_problems + misc_problems
)

print(f"Generating {len(all_problems)} problem files...")
for pid, title, diff, params, ptypes, rtype, starter, tests in all_problems:
    write_problem(pid, title, diff, params, ptypes, rtype, starter, tests)

print("Done!")
